apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      # ← pull private images from OCIR
      imagePullSecrets:
        - name: ocir-secret

      containers:
        - name: flask-app
          image: us-ashburn-1.ocir.io/ideguun3v2od/flask-app/flask-app:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "256Mi"
              cpu:    "250m"
            limits:
              memory: "512Mi"
              cpu:    "1"
          env:
            - name: CAPSTONE_TEST
              valueFrom:
                secretKeyRef:
                  name: capstone-secret
                  key:  CAPSTONE_TEST

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - name: http
      protocol: TCP
      port:       5000
      targetPort: 5000
